### ISSUE TITLE
User logs review (July 4th)

### ISSUE THREAD

**Issue by fczuardi** [calamar-io/calamarcopollo#33]
- I.F.
 - [ ] "Dia 04" #17 
 - [ ] "isso é uma data?" TBF (to be filed)
 - [ ] "Sim" #2

**Comment by GabrielSoga** [comment]
- V.M.S
  - [ ] "Extra Slugs" #60
  
- F.S.
  - [ ] "Domingo interfering with São Domingos" #61

- T.O.D.D.
  - [ ] " "Daqui 4 dias" is different then "dia 04" " #62

- G.A.
  - [ ] "More trip infos" #63
  - [ ] " [Sugesttion] Message reply when user wants to travel from a city to anywhere" #24 
  - [ ] " Not using the entity no "#64
